/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChatClient.java
 *
 * Created on Oct 4, 2009, 12:42:46 AM
 */
package cititool.chat.client.UI;

import cititool.chat.model.SystemConstants;
import cititool.chat.protocol.TransProtocol;
import cititool.util.EncryptHelper;
import cititool.util.NumberHelper;
import cititool.util.WindowHelper;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Administrator
 */
public class LoginFrame extends javax.swing.JFrame {

    /** Creates new form ChatClient */
    public LoginFrame() {
        initComponents();
        initdata();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        isSaveUser = new javax.swing.JCheckBox();
        isSavePass = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        clientSetting = new javax.swing.JTabbedPane();
        settingPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serverHostValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        serverPortValue = new javax.swing.JTextField();
        testServer = new javax.swing.JToggleButton();
        loadDataPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cititool.MainApp.class).getContext().getResourceMap(LoginFrame.class);
        setTitle(resourceMap.getString("LoginForm.title")); // NOI18N
        setName("LoginForm"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        username.setText(resourceMap.getString("username.text")); // NOI18N
        username.setName("username"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        loginBtn.setText(resourceMap.getString("loginBtn.text")); // NOI18N
        loginBtn.setName("loginBtn"); // NOI18N
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText(resourceMap.getString("registerBtn.text")); // NOI18N
        registerBtn.setName("registerBtn"); // NOI18N
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        isSaveUser.setText(resourceMap.getString("isSaveUser.text")); // NOI18N
        isSaveUser.setName("isSaveUser"); // NOI18N

        isSavePass.setText(resourceMap.getString("isSavePass.text")); // NOI18N
        isSavePass.setName("isSavePass"); // NOI18N

        password.setText(resourceMap.getString("password.text")); // NOI18N
        password.setName("password"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(loginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(registerBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(isSaveUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isSavePass))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isSaveUser)
                    .addComponent(isSavePass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(loginBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        clientSetting.setName("clientSetting"); // NOI18N

        settingPane.setName("settingPane"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        serverHostValue.setText(resourceMap.getString("serverHostValue.text")); // NOI18N
        serverHostValue.setName("serverHostValue"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        serverPortValue.setText(resourceMap.getString("serverPortValue.text")); // NOI18N
        serverPortValue.setName("serverPortValue"); // NOI18N

        testServer.setText(resourceMap.getString("testServer.text")); // NOI18N
        testServer.setName("testServer"); // NOI18N
        testServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingPaneLayout = new javax.swing.GroupLayout(settingPane);
        settingPane.setLayout(settingPaneLayout);
        settingPaneLayout.setHorizontalGroup(
            settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testServer)
                    .addGroup(settingPaneLayout.createSequentialGroup()
                        .addGroup(settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serverPortValue)
                            .addComponent(serverHostValue, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        settingPaneLayout.setVerticalGroup(
            settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serverHostValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(serverPortValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(testServer)
                .addGap(23, 23, 23))
        );

        clientSetting.addTab("setting", settingPane);

        loadDataPane.setName("loadDataPane"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        loginLog.setColumns(20);
        loginLog.setEditable(false);
        loginLog.setFont(resourceMap.getFont("仿宋"));
        loginLog.setForeground(resourceMap.getColor("loginLog.foreground")); // NOI18N
        loginLog.setLineWrap(true);
        loginLog.setRows(5);
        loginLog.setWrapStyleWord(true);
        loginLog.setName("loginLog"); // NOI18N
        jScrollPane1.setViewportView(loginLog);

        javax.swing.GroupLayout loadDataPaneLayout = new javax.swing.GroupLayout(loadDataPane);
        loadDataPane.setLayout(loadDataPaneLayout);
        loadDataPaneLayout.setHorizontalGroup(
            loadDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadDataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        loadDataPaneLayout.setVerticalGroup(
            loadDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadDataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        clientSetting.addTab(resourceMap.getString("loadDataPane.TabConstraints.tabTitle"), loadDataPane); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientSetting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:

        rDlg = new RegisterDlg(this, true);
        rDlg.pack();
        rDlg.setHost(serverHostValue.getText(), NumberHelper.string2Int(serverPortValue.getText(), 8888));
        WindowHelper.showCenter(rDlg);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        final String username = this.username.getText();
        final String userpass = EncryptHelper.encodeMd5(String.valueOf(this.password.getPassword()));

        try {
            final Socket s = new Socket(serverHostValue.getText(), NumberHelper.string2Int(serverPortValue.getText(), 8888));
            TransProtocol.requestLogin(username, userpass, s);
            String rstr = TransProtocol.getObject(s).toString();
            if (rstr.equals(SystemConstants.LOGON + "")) {
                Thread.sleep(500);
                this.setVisible(false);
                java.awt.EventQueue.invokeLater(new Runnable() {

                    public void run() {
                        JFrame frame = new UserInfoFrame(username, s);
                        frame.addWindowListener(new java.awt.event.WindowAdapter() {

                            public void windowClosing(java.awt.event.WindowEvent e) {
                                System.exit(0);
                            }
                        });
                        WindowHelper.showCenter(frame);

                    }
                });
            } else {
                JOptionPane.showMessageDialog(this, "user account does't exists!");
            }
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "login fail..check system connection");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "login fail..check system connection");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "login fail..check system connection");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void testServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testServerActionPerformed
        try {
            // TODO add your handling code here:
            Socket s = new Socket(serverHostValue.getText(), NumberHelper.string2Int(serverPortValue.getText(), 8888));
            TransProtocol.requestTestConn(s);
            String echo = TransProtocol.getObject(s).toString();
            if (echo.equals(SystemConstants.TESTSUC + "")) {
                JOptionPane.showMessageDialog(this, "connection success..");
            } else {
                JOptionPane.showMessageDialog(this, "connection fail..");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "connection fail..");
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this, "connection fail..");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "connection fail..");
        }
    }//GEN-LAST:event_testServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LoginFrame dialog = new LoginFrame();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane clientSetting;
    private javax.swing.JCheckBox isSavePass;
    private javax.swing.JCheckBox isSaveUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loadDataPane;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextArea loginLog;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField serverHostValue;
    private javax.swing.JTextField serverPortValue;
    private javax.swing.JPanel settingPane;
    private javax.swing.JToggleButton testServer;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    private RegisterDlg rDlg;

    public JTextArea getLog() {

        return loginLog;
    }

    private void initdata() {

        this.getRootPane().setDefaultButton(loginBtn);
    }
}
