/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemindMsgFrame.java
 *
 * Created on Dec 21, 2009, 11:29:31 AM
 */
package cititool.chat.client.com;

import cititool.util.WindowHelper;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.JTextPane;

/**
 *
 * @author zx04741
 */
public class RemindMsgFrame extends javax.swing.JFrame {

    /** Creates new form RemindMsgFrame */
    public RemindMsgFrame() {

        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.PLAIN_DIALOG);
        initComponents();
        WindowHelper.showRightBottom(this);
    }

    public RemindMsgFrame(String title){
        this();
        this.setTitle(title);
    }

    public JTextPane getContent(){

        return  jTextPane1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cititool.MainApp.class).getContext().getResourceMap(RemindMsgFrame.class);
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jScrollPane1.border.lineColor"), 2, true)); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jTextPane1.border.lineColor"), 2, true)); // NOI18N
        jTextPane1.setContentType(resourceMap.getString("jTextPane1.contentType")); // NOI18N
        jTextPane1.setEditable(false);
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               new RemindMsgFrame();

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
